apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9008  # FastAPI용 포트
    - protocol: TCP
      port: 6008
      targetPort: 6008  # gRPC용 포트